
const MESSAGES = {
  SUCCESS: 'Successful',
  FAILED : "Failed",
  PASSWORD_CHANGED_SUCCESSFULLY: 'Password changed successfully',
  CREDENTIALS_NOT_VALID: 'Credentials are not valid',
  PASSWORD_HAS_BEEN_RESET_SUCCESSFULLY: 'Password has been reset successfully',
  EMAIL_NOT_FOUND: 'Email Not Found',
  EMAIL_FOR_FORGET_PASSWORD_RESET: 'Email for Password Reset',
  EMAIL_CONTENT: function (email, token) {
    return `A password reset was requested for this email address ${email}.
    If you requested this reset, please 
    <a href="${process.env.FRONTEND_URL}resetPassword?token=${token}">Reset Your Password</a>`;
  },
  BENIFICARY_NOT_FOUND: 'Beneficiary not found',
  PASSCODE_RESET_SUCCESSFULLY : 'passcode reset successfully',
  BENIFICARY_EXISTS: 'benificary already exists',
  OTP_VERIFIED_SUCCESSFULLY: 'OTP verified successfully',
  TRANSACTION_CREATED: 'Transaction created successfully',
  TRANSACTION_NOT_FOUND: 'Transaction not found',
  PASSCODE_CHANGED_SUCCESSFULLY: 'Passcode changed successfully',
  OLD_PASSCODE_INCORRECT: 'Old passcode is incorrect',
  LOGIN_SUCCESS: 'Login successful',
  NOTIFICATION_SEND_FAILED: 'Notification send failed',
  OTP_SENT_SUCCESSFULLY: 'OTP sent successfully',
  TOKEN_NOT_VALID: 'Token not valid',
  PASSWORD_UPDATED_SUCCESSFUL: 'Password updated Successfuly',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  UNAUTHENTICATED: 'Unauthenticated',
  VERIFICATION_CODE_SENT_SUCCESSFULLY: 'Verification code sent successfully',
  OTP_HAS_ALREADY_VERIFIED: 'OTP has already verified',
  OTP_EXPIRED: 'OTP has expired',
  OTP_VERIFIED: 'OTP Verified',
  INVALID_OTP: 'Invalid OTP',
  EMAIL_VERIFIED_SUCCESSFULLY: 'Email verified successfully',
  NO_OTP_FOUND_OR_EXPIRED: 'No otp found or expired',
  OTP_GENERATED_SUCCESSFULLY: 'OTP generated successfully',
  OLD_PASSWORD_IS_INCORRECT: 'Old password is incorrect',
  IMAGE_FILE_IS_REQUIRED: 'Image file is required',
  TEAM_NOT_FOUND: 'Team not found',
  USER_NOT_FOUND: "User not found",
  EMAIL_NOT_FOUND_SIGN_UP: "Email not found, please enter the registered email.",
  MOBILE_NOT_FOUND_SIGN_UP: "Mobile not found, please enter the registered mobile.",
  INVITE_ALREADY_SENT: "Invite already sent to this user for this team.",
  VERIFICATION_PENDING: 'Verification pending, please verify your email first',
  EVENT_NOT_FOUND: 'Event not found',
  USER_ALREADY_EXISTS: 'User already exists with this phone number or email.',
  USER_ALREADY_EXISTS_LOGIN: 'User already exists with this email.Please login instead.',
  PASSCODES_DO_NOT_MATCH: 'Passcodes do not match',
  INVALID_REGISTRATION_STEP: 'Invalid registration step',
  REGISTRATION_COMPLETED_SUCCESSFULLY: 'Registration completed successfully',
  ALL_FILES_ARE_REQUIRED: 'All files (front, back, selfie) are required',
  KYC_INITIATED: 'KYC process initiated successfully',
  KYC_VERIFICATION_ACCEPTED: 'KYC verification accepted',
  KYC_VERIFICATION_DECLINED: 'KYC verification declined',
  KYC_VERIFICATION_PENDING: 'KYC verification is pending',
  KYC_REQUEST_NOT_FOUND: 'KYC request not found',
  FCM_TOKEN_REQUIRED: 'FCM token is required',
  FCM_TOKEN_UPDATED_SUCCESSFULLY: 'FCM token updated successfully',
  FCM_TOKEN_NOT_FOUND: 'FCM token not found',
  USI: {
    CHARGES_FETCHED_SUCCESSFULLY: 'Charges fetched successfully',
    REMITTER_ID_REQUIRED: 'Remitter ID is required',
    REMITTER_BENEFICIARIES_FETCHED_SUCCESSFULLY: 'Remitter beneficiaries fetched successfully',
    REMITTER_SEARCH_COMPLETED: 'Remitter search completed successfully',
    REMITTER_ID_OR_NAME_REQUIRED: 'Remitter ID or name is required',
    REQUIRED_FIELDS_MISSING: 'Required fields are missing',
    CHARGES_REQUIRED_FIELDS_MISSING: 'Charges required fields are missing',
    COLLECTION_POINTS_FETCHED_SUCCESSFULLY: 'Collection points fetched successfully',
    TRANSACTION_REF_REQUIRED: 'Transaction reference is required',
    TRANSACTION_REQUIRED_FIELDS_MISSING: 'Transaction required fields are missing',
    COUNTRY_REQUIRED: 'Country is required',
    BENEFICIARY_SEARCH_COMPLETED: 'Beneficiary search completed successfully',
    DEST_COUNTRY_REQUIRED: 'Destination country is required',
    SOURCE_CURRENCY_REQUIRED: 'Source currency is required',
    DESTINATION_CURRENCY_REQUIRED: 'Destination currency is required',
    DELIVERY_BANK_NAME_REQUIRED: 'Delivery bank name is required',
    RATES_FETCHED_SUCCESSFULLY: 'Rates fetched successfully',
    DESTINATION_COUNTRIES_FETCHED_SUCCESSFULLY: 'Destination countries fetched successfully',
    CURRENT_CREDIT_FETCHED_SUCCESSFULLY: 'Current credit fetched successfully',
    RATES_FETCHED_SUCCESSFULLY: 'Rates fetched successfully',
    DESTINATION_COUNTRIES_FETCH_FAILED: 'Failed to fetch destination countries',
    AGENT_DETAILS_FETCHED_SUCCESSFULLY: 'Agent details fetched successfully',
    AGENT_CREDIT_FETCHED_SUCCESSFULLY: 'Agent credit fetched successfully',
    REMITTER_CREATED_SUCCESSFULLY: 'Remitter created successfully',
    REMITTER_SEARCHED_SUCCESSFULLY: 'Remitter searched successfully',
    REMITTER_UPDATED_SUCCESSFULLY: 'Remitter updated successfully',
    BENEFICIARY_CREATED_SUCCESSFULLY: 'Beneficiary created successfully',
    BENEFICIARY_SEARCHED_SUCCESSFULLY: 'Beneficiary searched successfully',
    TRANSACTION_CREATED_SUCCESSFULLY: 'Transaction created successfully',
    TRANSACTION_CONFIRMED_SUCCESSFULLY: 'Transaction confirmed successfully',
    TRANSACTION_STATUS_FETCHED_SUCCESSFULLY: 'Transaction status fetched successfully',
    TRANSACTION_DETAILS_FETCHED_SUCCESSFULLY: 'Transaction details fetched successfully',
    REMITTER_TRANSACTIONS_FETCHED_SUCCESSFULLY: 'Remitter transactions fetched successfully',
    CHARGES_CALCULATED_SUCCESSFULLY: 'Charges calculated successfully',
    DELIVERY_BANKS_FETCHED_SUCCESSFULLY: 'Delivery banks fetched successfully',
    DELIVERY_BANKS_FETCH_FAILED: 'Failed to fetch delivery banks',
    INVALID_DESTINATION_COUNTRY: 'Invalid destination country',
    INVALID_SOURCE_CURRENCY: 'Invalid source currency',
    INVALID_DESTINATION_CURRENCY: 'Invalid destination currency',
    INVALID_DELIVERY_BANK_NAME: 'Invalid delivery bank name',
    TRANSACTION_NOT_FOUND: 'Transaction not found',
    REMITTER_NOT_FOUND: 'Remitter not found',
    BENEFICIARY_NOT_FOUND: 'Beneficiary not found',
    AGENT_NOT_FOUND: 'Agent not found',
    INVALID_TRANSACTION_ID: 'Invalid transaction ID',
    INVALID_SESSION_ID: 'Invalid session ID',
    INVALID_AGENT_ID: 'Invalid agent ID',
    INVALID_REMITTER_ID: 'Invalid remitter ID',
    INVALID_BENEFICIARY_ID: 'Invalid beneficiary ID',
    INVALID_CURRENCY_PAIR: 'Invalid currency pair',
    INVALID_RATE: 'Invalid rate',
    BENEFICIARY_REQUIRED_FIELDS_MISSING: 'Beneficiary required fields are missing',
    REMITTER_REQUIRED_FIELDS_MISSING: 'Remitter required fields are missing',
    TRANSACTION_REQUIRED_FIELDS_MISSING: 'Transaction required fields are missing',
    DELIVERY_BANKS_FETCH_FAILED: 'Failed to fetch delivery banks',
    COLLECTION_POINTS_FETCH_FAILED: 'Failed to fetch collection points',
  }
};

const TABLES = {
  USERS: 'Users',
  FORGETPASSWORDTOKENS: 'forgetPasswordTokens',
  KYC_REQUESTS: 'KycRequests',
  FCMS: 'Fcms',
  TRANSACTIONS: 'transactions',
  BENIFICARIES: 'benificaries',
  SCREENING_RESULTS: 'ScreeningResults',
  ADMIN_USERS: 'AdminUsers',
  AUDIT_LOGS: 'AuditLogs',
  ADMIN_SESSIONS: 'AdminSessions'
};

const MODELS = {
  USER: 'User',
  FORGETPASSWORDTOKEN: 'forgetPasswordToken',
  KYC_REQUEST: 'KycRequest',
  FCM: 'Fcm',
  TRANSACTION: 'transaction',
  BENIFICARY: 'benificary',
  SCREENING_RESULT: 'ScreeningResult',
  MLRO_FLAG: 'MLROFlag',
  ADMIN_USER: 'AdminUser',
  AUDIT_LOG: 'AuditLog',
  ADMIN_SESSION: 'AdminSession'
};

const STATUS = {
  PENDING: 'pending',
  ACCEPTED: 'accepted',
  REJECTED: 'rejected'
}

const ENUMS = {
  MYSELF: "my_self",
  BUSINESS: 'business',
  SOMEONE_ELSE: 'someone_else',
  PENDING: 'pending',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCLED: 'cancelled',
  REFUNDED: 'refunded',
  NOT_INITIATED:"not_initiated"
}


module.exports = {
  MESSAGES,
  TABLES,
  MODELS,
  STATUS,
  ENUMS
};
